package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/firebase/genkit/go/core"
	"github.com/firebase/genkit/go/genkit"
	"github.com/gorilla/websocket"
)

type ScenarioDefinition struct {
	Name     string `json:"name" jsonschema:"description=The scenario name or identifier used to label the test case."`
	Actor    string `json:"actor" jsonschema:"description=The actor in the scenario, representing the user persona in the app."`
	Action   string `json:"action" jsonschema:"description=The action the user takes in the scenario, used to drive message generation."`
	Expected string `json:"expected" jsonschema:"description=The expected outcome or response for the scenario."`
	Message  string `json:"message,omitempty" jsonschema:"description=The message generated by the first model based on the scenario's actor and action, used for evaluation."`
	Response string `json:"response,omitempty" jsonschema:"description=The actual response generated by the model for the scenario, used for evaluation."`
}

type ScenarioBuilder struct {
	scenario ScenarioDefinition
}

func Scenario(name string) *ScenarioBuilder {
	return &ScenarioBuilder{
		scenario: ScenarioDefinition{Name: name},
	}
}

func (sb *ScenarioBuilder) Given(actor string) *ScenarioBuilder {
	sb.scenario.Actor = actor
	return sb
}

func (sb *ScenarioBuilder) When(action string) *ScenarioBuilder {
	sb.scenario.Action = action
	return sb
}

func (sb *ScenarioBuilder) Then(expected string) *ScenarioBuilder {
	sb.scenario.Expected = expected
	return sb
}

type GenerateMessage struct {
	Actor  string `json:"actor" jsonschema:"description=The actor performing the action in the scenario, representing a user in the app. The first model simulates the message of a user using the chatbot, and this field defines that user role or persona for message generation."`
	Action string `json:"action" jsonschema:"description=The action that the actor is taking in the scenario. This represents the specific behavior or task that the model should perform when generating a message."`
}

type Messsage struct {
	Content string `json:"content" jsonschema:"description=The content of the message generated by the first model acting as the user in response to the scenario's actor and action."`
}

type BotPayload struct {
	Type    string `json:"type"`
	Payload struct {
		Text string `json:"text"`
	} `json:"payload"`
}

type ErrorPayload struct {
	Type    string `json:"type"`
	Payload struct {
		Message string `json:"message"`
	} `json:"payload"`
}

type Response struct {
	Content string `json:"content" jsonschema:"description=The content of the response generated by the model being evaluated, in response to the message generated for the scenario."`
}

type Score struct {
	IsSuccess bool   `json:"is_success" jsonschema:"description=Indicates whether the model's response was successful based on the evaluation criteria. This is a boolean value where true means the response met the success threshold (e.g., a score of 3 or above), and false means it did not."`
	Score     int    `json:"score" jsonschema:"description=The score for the scenario, on a scale of 0 to 5. 0 means the model's response was completely incorrect, while 5 means it was perfect."`
	Feedback  string `json:"feedback" jsonschema:"description=Detailed feedback on the model's response, explaining why it received the given score and how it could be improved."`
}

func NewReviewerFlow(ctx context.Context,
	g *genkit.Genkit,
	messageGeneratorFlow *core.Flow[*GenerateMessage, *Messsage, struct{}],
	evaluatorFlow *core.Flow[*ScenarioDefinition, *Score, struct{}],
	sendMessage func(ctx context.Context, message string) (*Response, error)) *core.Flow[*ScenarioDefinition, *Score, struct{}] {
	return genkit.DefineFlow(g, "reviewerFlow", func(ctx context.Context, scenario *ScenarioDefinition) (*Score, error) {
		message, err := messageGeneratorFlow.Run(ctx, &GenerateMessage{
			Actor:  scenario.Actor,
			Action: scenario.Action,
		})

		if err != nil {
			log.Println("Error running message generator flow:", err)
			return nil, err
		}
		
		scenario.Message = message.Content

		response, err := sendMessage(ctx, message.Content)
		if err != nil {
			log.Println("Error sending message:", err)
			return nil, err
		}

		scenario.Response = response.Content

		score, err := evaluatorFlow.Run(ctx, scenario)
		if err != nil {
			log.Println("Error running evaluator flow:", err)
			return nil, err
		}

		return score, nil
	})

}

func ReadScenarios() ([]ScenarioDefinition, error) {
	jsonFile, err := os.Open("scenarios.json")
	if err != nil {
		log.Println("Error opening scenarios file:", err)
		return nil, err
	}
	defer jsonFile.Close()

	var scenarios []ScenarioDefinition
	decoder := json.NewDecoder(jsonFile)
	err = decoder.Decode(&scenarios)
	if err != nil {
		log.Println("Error decoding scenarios JSON:", err)
		return nil, err
	}

	return scenarios, nil
}

func SendMessage(ctx context.Context, message string) (*Response, error) {
	c, _, err := websocket.DefaultDialer.Dial(cfg.WebsocketURL+"?token="+cfg.UserJWT, nil)
	if err != nil {
		log.Println("Error connecting to websocket:", err)
		return nil, err
	}
	defer c.Close()

	payload := map[string]any{
		"type": "user_message",
		"payload": map[string]string{
			"text": message,
		},
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		log.Println("Error marshalling message payload:", err)
		return nil, err
	}

	err = c.WriteMessage(websocket.BinaryMessage, payloadBytes)
	if err != nil {
		log.Println("Error sending message over websocket:", err)
		return nil, err
	}

	_, _, err = c.ReadMessage()
	if err != nil {
		log.Println("Error reading first message from websocket:", err)
		return nil, err
	}

	_, responseBytes, err := c.ReadMessage()
	if err != nil {
		log.Println("Error reading response from websocket:", err)
		return nil, err
	}

	var botResponse BotPayload
	err = json.Unmarshal(responseBytes, &botResponse)
	if err != nil {
		log.Println("Error unmarshalling bot response:", err)
		return nil, err
	}

	return &Response{Content: botResponse.Payload.Text}, nil
}

func SaveScores(scores []Score) {
	scoresFile, err := os.Create("scores.json")
	if err != nil {
		log.Println("Error creating scores file:", err)
		return
	}
	defer scoresFile.Close()

	encoder := json.NewEncoder(scoresFile)
	encoder.SetIndent("", "  ")
	err = encoder.Encode(scores)
	if err != nil {
		log.Println("Error encoding scores to JSON:", err)
		return
	}
}

func SummarizeScores(scores []Score) {
	var totalScore int
	var totalSuccess int
	for _, score := range scores {
		totalScore += score.Score
		if score.IsSuccess {
			totalSuccess++
		}
	}
	averageScore := float64(totalScore) / float64(len(scores))
	fmt.Printf("Average Score: %.2f\n", averageScore)
	fmt.Printf("Success Rate: %.2f%%\n", float64(totalSuccess)/float64(len(scores))*100)
}
